feat: добавлен функционал для работы со сделками
yluttsev/deals-rest-api pull request #1
Opened 2024-07-22 16:15 UTC by yluttsev

2024-07-23 11:03 UTC, gobaz095 requested changes

2024-07-23 11:03 UTC, gobaz095 commented on src/main/java/ru/luttsev/deals/job/SendMainBorrowerJob.java
> +        Outbox lastOutbox = outboxService.getLastMessage();
Ты берешь  1 самое последнее сообщение. А если у нас несколько неудачных отправок по разных контрагентам?
Нам же их всех надо отправить повторно.

2024-07-23 11:03 UTC, gobaz095 commented on src/main/resources/db/changesets/V3/V3__quartz_init.xml
В принципе можно так, а можно сослаться на исходник:

include:
file: classpath:org/quartz/impl/jdbcjobstore/liquibase.quartz.init.xml

2024-07-24 14:00 UTC, gobaz095 commented
Падают тесты с БД
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Failed to initialize dependency 'liquibase' of LoadTimeWeaverAware bean 'entityManagerFactory': Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Failed to instantiate [liquibase.integration.spring.SpringLiquibase]: Factory method 'liquibase' threw exception with message: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception with message: Failed to determine suitable jdbc url

2024-07-24 14:04 UTC, gobaz095 commented on src/main/java/ru/luttsev/deals/model/entity/ContractorRole.java
> +    public final boolean equals(Object o) {
Еще нужно проверять что типы совпадают

2024-07-24 14:05 UTC, gobaz095 commented on src/main/java/ru/luttsev/deals/model/entity/DealType.java
> +    public final boolean equals(Object o) {
Еще нужно проверять что типы совпадают и тд везде где у тебя equals переопределен :)

2024-07-25 12:56 UTC, gobaz095 requested changes

2024-07-25 12:56 UTC, gobaz095 commented on src/main/java/ru/luttsev/deals/repository/DealRepository.java
> +    @Query("select d_c.deal from DealContractor d_c where d_c.contractorId = :contractorId")
А что если у нас не одна сделка с этим контрагентом?

2024-07-25 12:56 UTC, gobaz095 commented on src/main/java/ru/luttsev/deals/service/impl/OutboxServiceImpl.java
> +    private boolean isResend(Outbox outbox) {
Идея в том, чтобы отправлять наличие активных сделок (одной или нескольких) по конкретному контрагенту, а ты предполагаешься что у нас 1 контрагент имеет строго 1 сделку.

2024-07-25 13:13 UTC, yluttsev commented on src/main/java/ru/luttsev/deals/repository/DealRepository.java
> +    @Query("select d_c.deal from DealContractor d_c where d_c.contractorId = :contractorId")
Запрос ищет основного заемщика в сделке, а по заданию у нас в сделке не может быть двух основных заемщиков

2024-07-27 14:35 UTC, merged